# Install script for directory: D:/PROJECT/OpenSceneGraph-3.5.1/examples

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "D:/PROJECT/OpenSceneGraph-3.5.1")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osg2cpp/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osganalysis/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osganimate/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgatomiccounter/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgautocapture/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgautotransform/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgbillboard/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgblenddrawbuffers/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgblendequation/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgcallback/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgcamera/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgcatch/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgclip/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgcompositeviewer/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgcopy/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgcubemap/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgdelaunay/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgcluster/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgdatabaserevisions/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgdepthpartition/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgdepthpeeling/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgdrawinstanced/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgdistortion/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgfadetext/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgfont/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgforest/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgfxbrowser/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgoutline/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osggameoflife/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osggeometry/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osggeometryshaders/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osghangglide/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osghud/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgimagesequence/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgimpostor/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgintersection/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgkdtree/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgkeyboard/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgkeyboardmouse/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgkeystone/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osglauncher/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osglight/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osglightpoint/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osglogicop/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osglogo/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osggpucull/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osggpx/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osggraphicscost/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgmanipulator/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgmovie/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgmultiplemovies/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgmultiplerendertargets/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgmultitexture/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgmultitexturecontrol/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgmultitouch/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgmultiviewpaging/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgoccluder/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgocclusionquery/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgoit/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgoscdevice/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgpackeddepthstencil/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgpagedlod/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgparametric/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgparticle/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgparticleeffects/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgparticleshader/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgpick/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgplanets/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgpoints/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgpointsprite/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgposter/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgprecipitation/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgprerender/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgprerendercubemap/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgreflect/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgrobot/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgSSBO/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgscalarbar/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgscribe/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgsequence/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgshaders/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgshadercomposition/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgshadergen/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgshaderterrain/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgshadow/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgshape/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgsharedarray/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgsimpleshaders/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgsimplifier/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgsimulation/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgsidebyside/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgslice/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgspacewarp/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgspheresegment/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgspotlight/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgstereoimage/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgstereomatch/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgterrain/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgthreadedterrain/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgtransferfunction/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgtext/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgtext3D/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgtexture1D/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgtexture2D/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgtexture2DArray/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgtexture3D/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgtexturerectangle/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgtexturecompression/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgthirdpersonview/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgtransformfeedback/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osguniformbuffer/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osguserstats/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgvertexprogram/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgvertexattributes/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgvolume/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgwindows/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgvirtualprogram/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osganimationhardware/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osganimationtimeline/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osganimationnode/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osganimationmakepath/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osganimationmorph/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osganimationskinning/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osganimationsolid/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osganimationviewer/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osganimationeasemotion/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgwidgetaddremove/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgwidgetbox/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgwidgetcanvas/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgwidgetframe/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgwidgetinput/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgwidgetlabel/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgwidgetmessagebox/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgwidgetmenu/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgwidgetnotebook/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgwidgetperformance/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgwidgetscrolled/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgwidgetshader/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgwidgetstyled/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgwidgettable/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgwidgetwindow/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osguserdata/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgsimplegl3/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgunittests/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgmemorytest/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgfpdepth/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgscreencapture/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgmotionblur/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgteapot/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgphotoalbum/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgtessellate/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgtessellationshaders/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgcomputeshaders/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgpdf/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgviewerQt/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgqfont/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgQtWidgets/cmake_install.cmake")
  include("D:/PROJECT/OpenSceneGraph-3.5.1/examples/osgQtBrowser/cmake_install.cmake")

endif()

